[package]
name = "rust_homepage"
version = "0.1.0"
edition = "2024"

[dependencies]
yew = {version = "^0.21", features = ["csr"]}
plotters = { version = "0.3", features = ["svg_backend"] }
plotters-canvas = "0.3"
web-sys = {version = "0.3", features = ["HtmlCanvasElement"]}

