services: 
  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    network_mode: "host"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./torborve_web:/usr/share/nginx/html/torborve_web:ro
      - /etc/letsencrypt/:/etc/letsencrypt:ro
