name: CI
on:
  push:
    branches:
      - main
      - dev
  pull_request:
## Inspired by https://github.com/simbleau/website
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4

      - name: Setup | Dependencies
        run: sudo apt update && sudo apt-get install -y libfontconfig1-dev libfontconfig1

      - name: Setup | Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build | Clippy
        run: cargo clippy -- -D warnings

      - name: Build | Rustfmt
        run: cargo fmt --all -- --check

  check:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4
      
      - name: Setup | Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build | Check (wasm)
        run: cargo check --target wasm32-unknown-unknown

  build:
    needs: check # Ensure check is run first.
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4

      - name: Setup | Trunk
        uses: jetli/trunk-action@v0.5.0
        with:
          version: "latest"

      - name: Setup | Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build | Trunk
        run: trunk build