name: CI
on: [push, pull_request]
## Inspired by https://github.com/simbleau/website
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4
      
      - name: Setup | Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build | Check (wasm)
        run: cargo check --target wasm32-unknown-unknown

  build:
    needs: check # Ensure check is run first.
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4

      - name: Setup | Trunk
        uses: jetli/trunk-action@v0.5.0
        with:
          version: "latest"

      - name: Setup | Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build | Trunk
        run: trunk build